# cleaning

Use the "Run" button to execute the code.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/Shareddrives/Data Anaytics with Python :NPTEL/flightlist_20200401_20200430.csv.gz', compression='gzip')

In [3]:
df

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day,latitude_1,longitude_1,altitude_1,latitude_2,longitude_2,altitude_2
0,HBAL102,NaN,a21c0f,NaN,NaN,NaN,NaN,2020-03-31 00:41:44+00:00,2020-04-01 22:50:47+00:00,2020-04-01 00:00:00+00:00,-4.821136,-76.319370,18288.0,-4.524902,-79.010274,2194.56
1,AUA1028,NaN,440081,OE-LPD,B772,YSSY,LOWW,2020-03-31 03:29:15+00:00,2020-04-01 00:41:43+00:00,2020-04-01 00:00:00+00:00,-33.963489,151.180630,0.0,48.117417,16.549988,NaN
2,ABW120,NaN,424564,VQ-BRJ,B748,KORD,UUEE,2020-03-31 07:07:17+00:00,2020-04-01 12:54:29+00:00,2020-04-01 00:00:00+00:00,41.965911,-87.883152,0.0,55.983490,37.495839,472.44
3,CSN461,CZ461,780da8,B-2026,B77L,KLAX,EDDF,2020-03-31 07:15:52+00:00,2020-04-01 12:02:53+00:00,2020-04-01 00:00:00+00:00,33.936302,-118.413963,0.0,50.035675,8.572299,45.72
4,ETH3730,NaN,04015c,NaN,NaN,OMSJ,EBLG,2020-03-31 08:05:10+00:00,2020-04-01 01:15:08+00:00,2020-04-01 00:00:00+00:00,25.386425,55.422139,609.6,50.634247,5.439027,76.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842900,SKQ33,NaN,a8f75b,N677ST,PC12,1NC8,KBUY,2020-04-30 23:46:16+00:00,2020-04-30 23:59:42+00:00,2020-04-30 00:00:00+00:00,35.545147,-80.236193,1524.0,36.035431,-79.459419,563.88
842901,N9989A,NaN,adf3ef,NaN,NaN,62GA,62GA,2020-04-30 23:46:41+00:00,2020-04-30 23:56:52+00:00,2020-04-30 00:00:00+00:00,33.379025,-83.897431,304.8,33.365158,-83.842987,640.08
842902,N853BP,NaN,abb2a4,N853BP,AS50,KEBG,KMFE,2020-04-30 23:46:46+00:00,2020-04-30 23:57:59+00:00,2020-04-30 00:00:00+00:00,26.423423,-98.138439,304.8,26.180191,-98.236481,30.48
842903,N5810F,NaN,a77bfd,N5810F,PRM1,KSNA,KF70,2020-04-30 23:46:48+00:00,2020-04-30 23:57:22+00:00,2020-04-30 00:00:00+00:00,33.667370,-117.874374,0.0,33.602057,-117.106934,609.60
842904,HKC320,RH320,780a43,B-LNW,A332,NaN,VHHH,2020-04-30 23:47:48+00:00,2020-04-30 23:58:56+00:00,2020-04-30 00:00:00+00:00,28.092957,113.977608,2133.6,22.306436,113.929799,-15.24

Datasets:

•	flightlist_20200401_20200430.csv.gz (main working file)

•	airport.csv (file to be joined with above)

Processing tasks:
1.	Remove all rows with no value for origin
2.	Remove all rows with no value for destination
3.	Remove columns:
-	number
-	icao24
-	registration
-	typecode
-	firstseen
-	lastseen
-	latitude_1
-	longitude_1
-	altitude_1
-	latitude_1
-	longitude_2
-	altitude_2
4.	Join airports.csv to main dataset:
o	Link gps_code to origin and join iso_region under new column orig_region
o	Link gps_code to destination and join iso_region under new column dest_region
o	Link gps_code to destination and join type under new column dest_type
5.	Use dest_region to remove all non-US regions
o	Only region formatted as US-XX should be kept
6.	Use orig_region to:
o	If origin_region = US-XX then create new column flight_type with value Domestic
o	If origin_region ≠ US-XX then fill flight_type column with value International
7.	Remove time from day column and keep only date YYYY-MM-DD
8.	Save file as .csv.gz

Final output sample:
callsign	origin	destination	orig_region	dest_region	dest_type	flight_type	day
DAL446	KLAX	KJFK	US-CA	US-NY	large_airport	Domestic	2020-04-01
DAL446	EDDF	KJFK	US-CA	US-NY	large_airport	International	2020-04-01

Remove all rows with no value for origin

In [5]:
df.isnull().sum()

callsign             0
number          649184
icao24               0
registration    110135
typecode        347497
origin          192084
destination     128031
firstseen            0
lastseen             0
day                  0
latitude_1           0
longitude_1          0
altitude_1           0
latitude_2          33
longitude_2         33
altitude_2       13127
dtype: int64

In [6]:
df = df.dropna(subset=['origin'])

In [7]:
df.shape

(650821, 16)

Remove all rows with no value for destination

In [8]:
df.isnull().sum()

callsign             0
number          507718
icao24               0
registration     78694
typecode        290871
origin               0
destination      88987
firstseen            0
lastseen             0
day                  0
latitude_1           0
longitude_1          0
altitude_1           0
latitude_2          24
longitude_2         24
altitude_2       10402
dtype: int64

In [9]:
df = df.dropna(subset=['destination'])

In [10]:
df.shape

(561834, 16)

In [11]:
df.isnull().sum()

callsign             0
number          446899
icao24               0
registration     66209
typecode        270336
origin               0
destination          0
firstseen            0
lastseen             0
day                  0
latitude_1           0
longitude_1          0
altitude_1           0
latitude_2          23
longitude_2         23
altitude_2       10343
dtype: int64

3.	Remove columns:
-	number
-	icao24
-	registration
-	typecode
-	firstseen
-	lastseen
-	latitude_1
-	longitude_1
-	altitude_1
-	latitude_1
-	longitude_2
-	altitude_2

In [12]:
df = df.drop(columns=['number', 'icao24', 'registration','typecode','firstseen','lastseen','latitude_1','longitude_1'
,'altitude_1','latitude_2','longitude_2','altitude_2'], axis=1)

In [13]:
df.shape

(561834, 4)

In [14]:
df

       callsign origin destination                        day
1       AUA1028   YSSY        LOWW  2020-04-01 00:00:00+00:00
2        ABW120   KORD        UUEE  2020-04-01 00:00:00+00:00
3        CSN461   KLAX        EDDF  2020-04-01 00:00:00+00:00
4       ETH3730   OMSJ        EBLG  2020-04-01 00:00:00+00:00
5        QTR895   OTHH        OTHH  2020-04-01 00:00:00+00:00
...         ...    ...         ...                        ...
842899   N800GX   KHYI        1TX4  2020-04-30 00:00:00+00:00
842900    SKQ33   1NC8        KBUY  2020-04-30 00:00:00+00:00
842901   N9989A   62GA        62GA  2020-04-30 00:00:00+00:00
842902   N853BP   KEBG        KMFE  2020-04-30 00:00:00+00:00
842903   N5810F   KSNA        KF70  2020-04-30 00:00:00+00:00

[561834 rows x 4 columns]

In [17]:
airports=pd.read_csv("/content/drive/Shareddrives/Data Anaytics with Python :NPTEL/airports.csv")

In [18]:
airports

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,NaN,US,US-AR,Newport,no,NaN,NaN,NaN,NaN,NaN,00AR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74569,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad
74570,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,NaN,NaN,NaN,NaN,NaN,NaN
74571,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,NaN,US,US-TX,Blum,no,87TX,NaN,87TX,NaN,NaN,NaN
74572,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,NaN,CA,CA-YT,(Old) Scandium City,no,NaN,NaN,NaN,NaN,NaN,"ZZZW, ZZZW, ZYW, YK96"
74573,313629,ZZZZ,small_airport,Satsuma Iōjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,NaN,RJX7,NaN,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

In [19]:
df = df.merge(airports[['gps_code','iso_region','type']], left_on='origin', right_on='gps_code', how='left')
df = df.rename(columns={'iso_region':'orig_region','type':'orig_type'})
df = df.merge(airports[['gps_code','iso_region','type']], left_on='destination', right_on='gps_code', how='left')
df = df.rename(columns={'iso_region':'dest_region','type':'dest_type'})

In [20]:
df

,callsign,origin,destination,day,gps_code_x,orig_region,orig_type,gps_code_y,dest_region,dest_type
0,AUA1028,YSSY,LOWW,2020-04-01 00:00:00+00:00,YSSY,AU-NSW,large_airport,LOWW,AT-9,large_airport
1,ABW120,KORD,UUEE,2020-04-01 00:00:00+00:00,KORD,US-IL,large_airport,UUEE,RU-MOS,large_airport
2,CSN461,KLAX,EDDF,2020-04-01 00:00:00+00:00,KLAX,US-CA,large_airport,EDDF,DE-HE,large_airport
3,ETH3730,OMSJ,EBLG,2020-04-01 00:00:00+00:00,OMSJ,AE-SH,large_airport,EBLG,BE-WLG,medium_airport
4,QTR895,OTHH,OTHH,2020-04-01 00:00:00+00:00,OTHH,QA-DA,large_airport,OTHH,QA-DA,large_airport
...,...,...,...,...,...,...,...,...,...,...
561829,N800GX,KHYI,1TX4,2020-04-30 00:00:00+00:00,KHYI,US-TX,medium_airport,1TX4,US-TX,small_airport
561830,SKQ33,1NC8,KBUY,2020-04-30 00:00:00+00:00,1NC8,US-NC,small_airport,KBUY,US-NC,small_airport
561831,N9989A,62GA,62GA,2020-04-30 00:00:00+00:00,62GA,US-GA,small_airport,62GA,US-GA,small_airport
561832,N853BP,KEBG,KMFE,2020-04-30 00:00:00+00:00,KEBG,US-TX,small_airport,KMFE,US-TX,medium_airport
561833,N5810F,KSNA,KF70,2020-04-30 00:00:00+00:00,KSNA,US-CA,large_airport,NaN,NaN,NaN

In [22]:
df['dest_region'].fillna('unknown', inplace=True)

In [23]:
df = df[df['dest_region'].str.startswith('US-')]

In [25]:
import numpy as np

In [26]:


# 6. Use orig_region to:
# If origin_region = US-XX then create new column flight_type with value Domestic
# If origin_region ≠ US-XX then fill flight_type column with value International
df['flight_type'] = np.where(df['orig_region'].str.startswith('US-'), 'Domestic', 'International')

# 7. Remove time from day column and keep only date YYYY-MM-DD
df['day'] = df['day'].str[:10]

# 8. Save file as .csv.gz
df.to_csv("main_dataset_processed.csv.gz", compression='gzip', index=False)

<ipython-input-26-c4bbb482c3ab>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['flight_type'] = np.where(df['orig_region'].str.startswith('US-'), 'Domestic', 'International')
<ipython-input-26-c4bbb482c3ab>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day'] = df['day'].str[:10]

In [28]:
df

,callsign,origin,destination,day,gps_code_x,orig_region,orig_type,gps_code_y,dest_region,dest_type,flight_type
22,UAL2793,VHHH,KORD,2020-04-01,VHHH,HK-NT,large_airport,KORD,US-IL,large_airport,International
24,PAC214,RKSI,KCVG,2020-04-01,RKSI,KR-28,large_airport,KCVG,US-KY,large_airport,International
26,KLM601,EHAM,KLAX,2020-04-01,EHAM,NL-NH,large_airport,KLAX,US-CA,large_airport,International
29,SOO276,VHHH,KCVG,2020-04-01,VHHH,HK-NT,large_airport,KCVG,US-KY,large_airport,International
30,LCO1308,SBBR,KMIA,2020-04-01,SBBR,BR-DF,large_airport,KMIA,US-FL,large_airport,International
...,...,...,...,...,...,...,...,...,...,...,...
561828,N421BL,KRDU,KRDU,2020-04-30,KRDU,US-NC,large_airport,KRDU,US-NC,large_airport,Domestic
561829,N800GX,KHYI,1TX4,2020-04-30,KHYI,US-TX,medium_airport,1TX4,US-TX,small_airport,Domestic
561830,SKQ33,1NC8,KBUY,2020-04-30,1NC8,US-NC,small_airport,KBUY,US-NC,small_airport,Domestic
561831,N9989A,62GA,62GA,2020-04-30,62GA,US-GA,small_airport,62GA,US-GA,small_airport,Domestic
561832,N853BP,KEBG,KMFE,2020-04-30,KEBG,US-TX,small_airport,KMFE,US-TX,medium_airport,Domestic